apiVersion: v1
kind: Service
metadata:
  name: tp-app-service
  namespace: tp-app
spec:
  type: LoadBalancer     
  selector:
    app: tp-app           
  ports:
    - protocol: TCP
      port: 80           
      targetPort: 8000   